name: analysis_utils
description:
version: 0.0.1
homepage: https://www.github.com/Rodsevich/analysis_utils
author: Rodsevich <nicorodsevich@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: '^0.31.1'
  source_span: '^1.4.0'

dev_dependencies:
  test: ^0.12.0
